service: multenv
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'prod'}
  environment: ${file(./config/env.${self:provider.stage}.json)}
  iam:
    role:
      statements: ${file(./config/serverless/db.iam.role.yaml)}

functions:
  scheduler:
    handler: src/index.scheduler
    events:
      - schedule:
          rate: ${self:custom.schedulerRate}
          name: schedule-commit-message-${self:provider.stage}
          description: get commit message every minutes
          enabled: ${self:custom.enabled}

custom:
  schedulerRate: rate(1 minute)
  enabled: true
  tableName: ${self:provider.environment.DbTableName}
  dbReadCapacityUnits: ${self:provider.environment.ReadCapacityUnits}
  dbWriteCapacityUnits: ${self:provider.environment.WriteCapacityUnits}

resources:
  Resources: ${file(./config/serverless/resources/dynamoCommitMessages.table.yaml)}
